DROP TYPE IF EXISTS PRODUCT_CONDITION;

CREATE TYPE PRODUCT_CONDITION AS ENUM('new', 'second');

CREATE TABLE PRODUCTS (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(60) NOT NULL,
    PRICE DECIMAL(20,0) NOT NULL,
    STOCK INT NOT NULL,
    CONDITION PRODUCT_CONDITION NOT NULL,
    IS_PURCHASABLE BOOLEAN NOT NULL,
    PURCHASE_COUNT INT NOT NULL,
    TAGS TEXT NOT NULL,
    IMAGE_URL TEXT NOT NULL,
    USER_ID INT NOT NULL,
    CREATED_AT BIGINT NOT NULL,
    UPDATED_AT BIGINT NOT NULL,
    CONSTRAINT fk_products_user FOREIGN KEY(USER_ID) REFERENCES USERS(id)
);
