CREATE TABLE PAYMENTS (
    ID SERIAL PRIMARY KEY,
    USER_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    BANK_ID INT NOT NULL,
    QUANTITY INT NOT NULL,
    PAYMENT_PROOF_IMAGE_URL TEXT NOT NULL,
    CREATED_AT BIGINT NOT NULL,
    UPDATED_AT BIGINT NOT NULL,
    CONSTRAINT fk_payment_users FOREIGN KEY(USER_ID) REFERENCES USERS(id),
    CONSTRAINT fk_payment_products FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(id),
    CONSTRAINT fk_payment_banks FOREIGN KEY(BANK_ID) REFERENCES BANKS(id)
);