CREATE TABLE USERS (
    ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(15) UNIQUE NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    PASSWORD TEXT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT now (),
    UPDATED_AT TIMESTAMP DEFAULT now ()
);
